[deps]
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
AtomsBuilder = "f5cc8831-eeb7-4288-8d9f-d6c1ddb77004"
AtomsIO = "1692102d-eeb4-4df9-807b-c9517f998d44"
AtomsView = "ee286e10-dd2d-4ff2-afcb-0a3cd50c8041"
Brillouin = "23470ee3-d0df-4052-8b1a-8cbd6363e7f0"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DFTK = "acf6eb54-70d9-11e9-0013-234b7a5f5337"
DftFunctionals = "6bd331d2-b28d-4fd3-880e-1a1c7f37947f"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PseudoPotentialData = "5751a51d-ac76-4487-a056-413ecf6fbe19"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"
