[deps]
ASEconvert = "3da9722f-58c2-4165-81be-b4d7253e8fd2"
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
AtomsIO = "1692102d-eeb4-4df9-807b-c9517f998d44"
AtomsView = "ee286e10-dd2d-4ff2-afcb-0a3cd50c8041"
DFTK = "acf6eb54-70d9-11e9-0013-234b7a5f5337"
DftFunctionals = "6bd331d2-b28d-4fd3-880e-1a1c7f37947f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PseudoPotentialData = "5751a51d-ac76-4487-a056-413ecf6fbe19"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
